name: Testes Mobile com Robot

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  robot-tests:
    runs-on: self-hosted

    steps:
      - name: Iniciar emulador
        run: |
          export ANDROID_AVD_HOME=/home/runner/.config/.android/avd
          $HOME/android-sdk/emulator/emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          booted=""
          until [[ "$booted" == "1" ]]; do
            booted=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            sleep 2
          done
          echo "Emulador pronto!"

      - name: Iniciar Appium
        run: |
          npx appium --log appium.log &
          echo "Aguardando o Appium iniciar..."
          for i in {1..15}; do
            if curl -s http://localhost:4723/wd/hub/status | grep -q "status"; then
              echo "Appium está rodando!"
              break
            fi
            echo "Esperando Appium... ($i/15)"
            sleep 2
          done

      - name: Executar testes Robot Framework
        run: robot --timestampoutputs -d results tests/home.robot
